In [34]:
import numpy as np
import pandas as pd
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
 'color': ['white','red','red','black','green'],
 'brand': ['OMG','ABC','ABC','POD','POD']})

In [35]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [36]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
'brand': ['OMG','POD','ABC','POD']})

In [37]:

frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [38]:
pd.merge(frame1,frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [39]:
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [40]:
pd.merge(frame1,frame2,on='brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [41]:
frame2.columns = ['brand','sid']
frame2

brand  sid
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [42]:
pd.merge(frame1, frame2, left_on='id', right_on='sid')


Empty DataFrame
Columns: [id, color, brand_x, brand_y, sid]
Index: []

In [43]:
frame2.columns = ['brand','id']

In [44]:
pd.merge(frame1,frame2,on='id')

Empty DataFrame
Columns: [id, color, brand_x, brand_y]
Index: []

In [45]:
pd.merge(frame1,frame2,on='id',how='outer')

id  color brand_x brand_y
0     ball  white     OMG     NaN
1   pencil    red     ABC     NaN
2      pen    red     ABC     NaN
3      mug  black     POD     NaN
4  ashtray  green     POD     NaN
5      OMG    NaN     NaN  pencil
6      POD    NaN     NaN  pencil
7      POD    NaN     NaN     pen
8      ABC    NaN     NaN    ball

In [46]:
pd.merge(frame1,frame2,on='id',how='left')

id  color brand_x brand_y
0     ball  white     OMG     NaN
1   pencil    red     ABC     NaN
2      pen    red     ABC     NaN
3      mug  black     POD     NaN
4  ashtray  green     POD     NaN

In [47]:
pd.merge(frame1,frame2,on=['id','brand'],how='outer')

id  color   brand
0     ball  white     OMG
1   pencil    red     ABC
2      pen    red     ABC
3      mug  black     POD
4  ashtray  green     POD
5      OMG    NaN  pencil
6      POD    NaN  pencil
7      ABC    NaN    ball
8      POD    NaN     pen

In [48]:
pd.merge(frame1,frame2,right_index=True, left_index=True)

id_x  color brand_x brand_y id_y
0    ball  white     OMG  pencil  OMG
1  pencil    red     ABC  pencil  POD
2     pen    red     ABC    ball  ABC
3     mug  black     POD     pen  POD

In [49]:
frame2.columns = ['brand2','id2']
frame1.join(frame2)

id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3      mug  black   POD     pen  POD
4  ashtray  green   POD     NaN  NaN

In [50]:
array1 = np.arange(9).reshape((3,3))

In [51]:
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
array2 = np.arange(9).reshape((3,3))+6
>>> array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [53]:
np.concatenate([array1,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [54]:
np.concatenate([array1,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [55]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])

In [56]:
ser1 

1    0.137262
2    0.969014
3    0.238296
4    0.792722
dtype: float64

In [57]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
>>> ser2

5    0.929851
6    0.914878
7    0.275234
8    0.861138
dtype: float64

In [58]:
pd.concat([ser1,ser2])

1    0.137262
2    0.969014
3    0.238296
4    0.792722
5    0.929851
6    0.914878
7    0.275234
8    0.861138
dtype: float64

In [59]:
pd.concat([ser1,ser2],axis=1)

0         1
1  0.137262       NaN
2  0.969014       NaN
3  0.238296       NaN
4  0.792722       NaN
5       NaN  0.929851
6       NaN  0.914878
7       NaN  0.275234
8       NaN  0.861138

In [60]:
pd.concat([ser1,ser2], keys=[1,2])

1  1    0.137262
   2    0.969014
   3    0.238296
   4    0.792722
2  5    0.929851
   6    0.914878
   7    0.275234
   8    0.861138
dtype: float64

In [61]:
frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[1,2,3],
columns=['A','B','C'])
frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[4,5,6],
columns=['A','B','C'])
pd.concat([frame1, frame2])

A         B         C
1  0.073431  0.671611  0.020801
2  0.579247  0.275557  0.084883
3  0.191771  0.209932  0.350297
4  0.056063  0.823453  0.951352
5  0.380592  0.269270  0.307480
6  0.282822  0.701219  0.810040

In [62]:
pd.concat([frame1, frame2], axis=1)

A         B         C         A         B         C
1  0.073431  0.671611  0.020801       NaN       NaN       NaN
2  0.579247  0.275557  0.084883       NaN       NaN       NaN
3  0.191771  0.209932  0.350297       NaN       NaN       NaN
4       NaN       NaN       NaN  0.056063  0.823453  0.951352
5       NaN       NaN       NaN  0.380592  0.269270  0.307480
6       NaN       NaN       NaN  0.282822  0.701219  0.810040

In [63]:
#Combining
ser1.combine_first(ser2)

1    0.137262
2    0.969014
3    0.238296
4    0.792722
5    0.929851
6    0.914878
7    0.275234
8    0.861138
dtype: float64

In [64]:
ser2.combine_first(ser1)

1    0.137262
2    0.969014
3    0.238296
4    0.792722
5    0.929851
6    0.914878
7    0.275234
8    0.861138
dtype: float64

In [65]:
ser1[:3].combine_first(ser2[:3])

1    0.137262
2    0.969014
3    0.238296
5    0.929851
6    0.914878
7    0.275234
dtype: float64

In [66]:
#PIVOTING
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
index=['white','black','red'],
columns=['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [67]:
ser5 = frame1.stack()
ser5

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int32

In [68]:
ser5.unstack()

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [69]:
longframe = pd.DataFrame({ 'color':['white','white','white',
... 'red','red','red',
... 'black','black','black'],
... 'item':['ball','pen','mug',
... 'ball','pen','mug',
... 'ball','pen','mug'],
... 'value': np.random.rand(9)})
longframe

color  item     value
0  white  ball  0.886192
1  white   pen  0.983343
2  white   mug  0.407956
3    red  ball  0.106340
4    red   pen  0.373792
5    red   mug  0.138804
6  black  ball  0.713195
7  black   pen  0.785233
8  black   mug  0.793410

In [70]:
wideframe = longframe.pivot('color','item')
>>> wideframe

value                    
item       ball       mug       pen
color                              
black  0.713195  0.793410  0.785233
red    0.106340  0.138804  0.373792
white  0.886192  0.407956  0.983343

In [71]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
... index=['white','black','red'],
... columns=['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [72]:
frame1.drop('white')

ball  pen  pencil
black     3    4       5
red       6    7       8

In [73]:
del frame1['ball']

In [74]:
frame1

pen  pencil
white    1       2
black    4       5
red      7       8

In [75]:
#pivot from long to wide format

In [76]:
longframe = pd.DataFrame({ 'color':['white','white','white',
... 'red','red','red',
... 'black','black','black'],
... 'item':['ball','pen','mug',
... 'ball','pen','mug',
... 'ball','pen','mug'],
... 'value': np.random.rand(9)})

In [77]:
longframe

color  item     value
0  white  ball  0.575241
1  white   pen  0.380074
2  white   mug  0.985256
3    red  ball  0.425122
4    red   pen  0.697368
5    red   mug  0.711131
6  black  ball  0.302294
7  black   pen  0.245789
8  black   mug  0.386358

In [78]:
wideframe = longframe.pivot('color','item')

In [79]:
wideframe

value                    
item       ball       mug       pen
color                              
black  0.302294  0.386358  0.245789
red    0.425122  0.711131  0.697368
white  0.575241  0.985256  0.380074

In [80]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
... index=['white','black','red'],
... columns=['ball','pen','pencil'])

In [81]:
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [82]:
del frame1['ball']

In [83]:
frame1

pen  pencil
white    1       2
black    4       5
red      7       8

In [84]:
frame1.drop('white')

pen  pencil
black    4       5
red      7       8

In [90]:
#REMOVING DUPLICATE
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],
'value': [2,1,3,3,2]})

In [91]:
dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [92]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [93]:
dframe[dframe.duplicated()]

color  value
3    red      3
4  white      2

In [94]:
#Mapping
map = {
'label1' : 'value1',
'label2' : 'value2',
}

In [95]:
#REPLACING VIA MAPPING
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
'color':['white','rosso','verde','black','yellow'],
'price':[5.56,4.20,1.30,0.56,2.75]})

In [96]:
frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [97]:
newcolors = {
'rosso': 'red',
'verde': 'green'
}

In [98]:
frame.replace(newcolors)

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [103]:
newitem= {
    'pen':'feltpen',
    'mug':'jug'
    
}

In [104]:
frame.replace(newitem)

item   color  price
0     ball   white   5.56
1      jug   rosso   4.20
2  feltpen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [110]:
prices = {
... 'ball' : 5.56,
... 'mug' : 4.20,
... 'bottle' : 1.30,
... 'scissors' : 3.41,
... 'pen' : 1.30,
... 'pencil' : 0.56,
... 'ashtray' : 2.75
}

In [111]:
frame['price'] = frame['item'].map(prices)

In [112]:
frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [113]:
reindex = {
... 0: 'first',
... 1: 'second',
... 2: 'third',
... 3: 'fourth',
... 4: 'fifth'}

In [114]:
frame.rename(reindex)

item   color  price
first      ball   white   5.56
second      mug   rosso   4.20
third       pen   verde   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [118]:
recolumn = {
... 'item':'object',
... 'price': 'value'}
>>> frame.rename(index=reindex, columns=recolumn)

object   color  value
first      ball   white   5.56
second      mug   rosso   4.20
third       pen   verde   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [116]:
frame.rename(columns={'item':'object'}, inplace=True)
>>> frame

object   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [119]:
#dicretization and binning
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]

In [120]:
bins = [0,25,50,75,100]

In [121]:
cat = pd.cut(results, bins)

In [122]:
cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [123]:
cat.categories

IntervalIndex([(0, 25], (25, 50], (50, 75], (75, 100]],
              closed='right',
              dtype='interval[int64]')

In [124]:
cat.codes

array([0, 1, 2, 2, 1, 3, 3, 0, 0, 2, 2, 1, 3, 0, 1, 3, 3], dtype=int8)

In [143]:
randframe = pd.DataFrame(np.random.rand(1000,3))

ValueError: low >= high

In [128]:
randframe.describe()

0            1            2
count  1000.000000  1000.000000  1000.000000
mean     -0.007578     0.015150    -0.009284
std       1.006641     1.013686     0.999744
min      -3.136048    -3.373160    -2.991427
25%      -0.757157    -0.655399    -0.681800
50%       0.015958    -0.002811    -0.007094
75%       0.701377     0.728364     0.659879
max       2.688001     3.785058     3.630155

In [134]:
randframe.std()

0    0.288317
1    0.285876
2    0.286415
dtype: float64

In [136]:
randframe[(np.abs(randframe) > (3*randframe.std())).any(1)]

0         1         2
5    0.064603  0.864690  0.730745
6    0.715938  0.872100  0.159033
9    0.882121  0.349059  0.972149
10   0.257308  0.906826  0.166059
18   0.233365  0.732702  0.872099
..        ...       ...       ...
987  0.846562  0.789399  0.897080
992  0.653191  0.140703  0.965419
995  0.928163  0.417802  0.606090
998  0.572224  0.261080  0.935348
999  0.789512  0.996436  0.930292

[368 rows x 3 columns]

In [140]:
nframe = pd.DataFrame(np.arange(25).reshape(5,5))

In [141]:
nframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [142]:
new_order =[2,4,3]
nframe.take(new_order)

0   1   2   3   4
2  10  11  12  13  14
4  20  21  22  23  24
3  15  16  17  18  19

In [146]:
sample = np.random.randint(0, len(nframe), size=3)
sample

array([3, 0, 0])

In [147]:
nframe.take(sample)

0   1   2   3   4
3  15  16  17  18  19
0   0   1   2   3   4
0   0   1   2   3   4

In [149]:
#string manupulation
text = '16 Bolton Avenue , Boston'
text.split(',')

['16 Bolton Avenue ', ' Boston']

In [150]:
tokens = [s.strip() for s in text.split(',')]

In [151]:
tokens

['16 Bolton Avenue', 'Boston']

In [152]:
strings = ['A+','A','A-','B','BB','BBB','C+']

In [155]:
'.'.join(strings)

'A+.A.A-.B.BB.BBB.C+'

In [158]:
import re
text = "This is an\t odd \n text!"
re.split('\s+', text)

['This', 'is', 'an', 'odd', 'text!']

In [162]:
#DATA AGGREGATION
frame = pd.DataFrame({ 'color': ['white','red','green','red','green'],
'object': ['pen','pencil','pencil','ashtray','pen'],
'price1' : [5.56,4.20,1.30,0.56,2.75],
'price2' : [4.75,4.12,1.60,0.75,3.15]})
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [163]:
group = frame['price1'].groupby(frame['color'])

In [164]:
group

In [165]:
group.groups

{'green': [2, 4], 'red': [1, 3], 'white': [0]}

In [166]:
group.mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [183]:
group=frame[['price1','price2']].groupby([frame['color'],frame['object']])

In [184]:
group.mean()

price1  price2
color object                 
green pen        2.75    3.15
      pencil     1.30    1.60
red   ashtray    0.56    0.75
      pencil     4.20    4.12
white pen        5.56    4.75

In [185]:
ggroup = frame['price1'].groupby([frame['color'],frame['object']])
>>> ggroup.groups

{('green', 'pen'): [4], ('green', 'pencil'): [2], ('red', 'ashtray'): [3], ('red', 'pencil'): [1], ('white', 'pen'): [0]}

In [186]:
ggroup.sum()

color  object 
green  pen        2.75
       pencil     1.30
red    ashtray    0.56
       pencil     4.20
white  pen        5.56
Name: price1, dtype: float64

In [187]:
for name, group in frame.groupby('color'):

SyntaxError: unexpected EOF while parsing (<ipython-input-187-6c09f7a6ccc9>, line 1)

In [191]:
def range(series):
    return series.max() - series.min()
group['price1'].agg(range)

color  object 
green  pen        0.0
       pencil     0.0
red    ashtray    0.0
       pencil     0.0
white  pen        0.0
Name: price1, dtype: float64

In [192]:
frame = pd.DataFrame({ 'color':['white','red','green','red','green'],
... 'price1':[5.56,4.20,1.30,0.56,2.75],
... 'price2':[4.75,4.12,1.60,0.75,3.15]})
>>> frame

color  price1  price2
0  white    5.56    4.75
1    red    4.20    4.12
2  green    1.30    1.60
3    red    0.56    0.75
4  green    2.75    3.15

In [193]:
sums = frame.groupby('color').sum().add_prefix('tot_')
>>> sums

tot_price1  tot_price2
color                        
green        4.05        4.75
red          4.76        4.87
white        5.56        4.75

In [194]:
merge(frame,sums,left_on='color',right_index=True)

NameError: name 'merge' is not defined

In [195]:
frame.groupby('color').transform(np.sum).add_prefix('tot_')

tot_price1  tot_price2
0        5.56        4.75
1        4.76        4.87
2        4.05        4.75
3        4.76        4.87
4        4.05        4.75

In [196]:
frame = pd.DataFrame( { 'color':['white','black','white','white','black','black'],
... 'status':['up','up','down','down','down','up'],
... 'value1':[12.33,14.55,22.34,27.84,23.40,18.33],
... 'value2':[11.23,31.80,29.99,31.18,18.25,22.44]})
>>> frame

color status  value1  value2
0  white     up   12.33   11.23
1  black     up   14.55   31.80
2  white   down   22.34   29.99
3  white   down   27.84   31.18
4  black   down   23.40   18.25
5  black     up   18.33   22.44

In [197]:
frame.groupby(['color','status']).apply( lambda x: x.max())

color status  value1  value2
color status                              
black down    black   down   23.40   18.25
      up      black     up   18.33   31.80
white down    white   down   27.84   31.18
      up      white     up   12.33   11.23

In [198]:
timeseries = pd.Series(np.random.rand(10), index=temp)

NameError: name 'temp' is not defined

In [199]:
temp = pd.date_range('1/1/2015', periods=10, freq= 'H')

In [200]:
temp

DatetimeIndex(['2015-01-01 00:00:00', '2015-01-01 01:00:00',
               '2015-01-01 02:00:00', '2015-01-01 03:00:00',
               '2015-01-01 04:00:00', '2015-01-01 05:00:00',
               '2015-01-01 06:00:00', '2015-01-01 07:00:00',
               '2015-01-01 08:00:00', '2015-01-01 09:00:00'],
              dtype='datetime64[ns]', freq='H')

In [201]:
timetable = pd.DataFrame( {'date': temp, 'value1' : np.random.rand(10),
... 'value2' : np.random.rand(10)})

In [202]:
timetable

date    value1    value2
0 2015-01-01 00:00:00  0.026069  0.368760
1 2015-01-01 01:00:00  0.754762  0.248729
2 2015-01-01 02:00:00  0.594514  0.612442
3 2015-01-01 03:00:00  0.920288  0.287540
4 2015-01-01 04:00:00  0.987480  0.770360
5 2015-01-01 05:00:00  0.293668  0.806545
6 2015-01-01 06:00:00  0.626050  0.446698
7 2015-01-01 07:00:00  0.840793  0.841862
8 2015-01-01 08:00:00  0.795530  0.173982
9 2015-01-01 09:00:00  0.780662  0.854908